version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/sre.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - slicenet
  app:
    build: ./app
    networks:
      - slicenet
  monitor_app:
    build: monitor
    depends_on:
      - nginx
    networks:
      - slicenet
networks:
  slicenet: 
    driver: bridge

